### ISSUE TITLE
Roadmap [Late-2022/Early-2023]

### ISSUE THREAD

**Issue by 29TB** [TeamUtils/bookmarklets#19]
# To-Do List

## Total
- [ ] https://github.com/TeamUtils/bookmarklets/issues/15
- [ ] https://github.com/TeamUtils/bookmarklets/issues/16
- [ ] https://github.com/TeamUtils/bookmarklets/issues/17
- [ ] https://github.com/TeamUtils/bookmarklets/issues/18

## Good-First Issues
- [ ] #15
- [ ] #16 

## Others/Advanced
- [ ] #18
- [ ] #17
